package com.project.flight.enums;
/** http://www.iata.org/publications/Pages/code-search.aspx **/
public enum AirlineEnum {
    AZU_AD("AD","AZU","Azul Linhas Aereas","Azul Linhas Aereas","Brazil"),
    GLO_G3("G3","GLO","GOL Transportes Aereos","GOL Transportes Aereos","Brazil"),
    TAM_JJ("JJ","TAM","TAM Linhas Aereas","TAM Linhas Aereas","Brazil"),
    TUS_M3("M3","TUS","ABSA Aerolinhas","ABSA Aerolinhas","Brazil"),
    ONE_O6("O6","ONE","Avianca Brazil","Avianca Brazil","Brazil"),
    PTB_P3("P3","PTB","Passaredo Transportes Aereos","Passaredo Transportes Aereos","Brazil"),
    PTN_P8("P8","PTN","Pantanal Linhas Aereas","Pantanal Linhas Aereas","Brazil"),
    TSD_R9("R9","TSD","TAF Linhas Aereas","TAF Linhas Aereas","Brazil"),
    RIO_RL("RL","RIO","Rio Linhas Aereas","Rio Linhas Aereas","Brazil"),
    TIB_T4("T4","TIB","TRIP Linhas Aereas","TRIP Linhas Aereas","Brazil"),
    WEB_WH("WH","WEB","Webjet Linhas Aéreas","Webjet Linhas Aéreas","Brazil"),
    AFR_AF("AF","AFR","Air France","Air France","France"),
    TAP_TP("TP","TAP","TAP Portugal","TAP Portugal","Portugal"),
    DLH_LH("LH","DLH","Lufthansa","Lufthansa","Germany"),
    BAW_BA("BA","BAW","British Airways","British Airways","United Kingdom"),
    JOR_0B("0B","JOR","Blue Air  Blue Transport","Blue Air  Blue Transport","Romania"),
    JCS_0J("0J","JCS","Jetclub Jetclub","Jetclub Jetclub","Switzerland"),
    TGV_2C("2C","TGV","SNCF","SNCF","France"),
    DBB_2A("2A","DBB","Deutsche Bahn","Deutsche Bahn","Germany"),
    VRR_2R("2R","VRR","VIA Rail Canada","VIA Rail Canada","Canada"),
    VFC_0V("0V","VFC","VASCO Vietnam Air Service Company","VASCO Vietnam Air Service Company","Vietnam"),
    BGH_1B("1B","BGH","BH Air","BH Air","Bulgaria"),
    AMB_1I("1I","AMB","Deutsche Rettungsflugwacht","Deutsche Rettungsflugwacht","Germany"),
    EJA_1I("1I","EJA","Netjets","Netjets","USA"),
    NVR_1I("1I","NVR","Novair/Nova Airlines","Novair/Nova Airlines","Sweden"),
    BUC_1T("1T","BUC","Bulgarian Air Charter","Bulgarian Air Charter","Bulgaria"),
    OST_2D("2D","OST","Alania Airlines","Alania Airlines","Russia"),
    PHW_2E("2E","PHW","AVE.com","AVE.com","United Arab Emirates"),
    FTA_2F("2F","FTA","Frontier Alaska/Frontier Flying Service","Frontier Alaska/Frontier Flying Service","USA"),
    IRP_2F("2F","IRP","Payam/IPTAS","Payam/IPTAS","Iran"),
    SRU_2I("2I","SRU","Star Peru","Star Peru","Peru"),
    VBW_2J("2J","VBW","Air Burkina","Air Burkina","Burkina Faso"),
    GLG_2K("2K","GLG","Aerogal Aerolineas Galapagos","Aerogal Aerolineas Galapagos","Ecuador"),
    OAW_2L("2L","OAW","Helvetic Airways","Helvetic Airways","Switzerland"),
    MDV_2M("2M","MDV","Moldavian Airlines","Moldavian Airlines","Moldova"),
    NTJ_2N("2N","NTJ","Nextjet","Nextjet","Sweden"),
    UMK_2N("2N","UMK","Yuzmashavia","Yuzmashavia","Ukraine"),
    GAP_2P("2P","GAP","Air Philippines","Air Philippines","Philippines"),
    SNC_2Q("2Q","SNC","Air Cargo Carriers","Air Cargo Carriers","USA"),
    SDY_2S("2S","SDY","Island Express","Island Express","USA"),
    ANH_2T("2T","ANH","Alajnihah Airways","Alajnihah Airways","Libya"),
    WLC_2W("2W","WLC","Welcome Air","Welcome Air","Austria"),
    CGN_2Z("2Z","CGN","Changan Airlines","Changan Airlines","China"),
    CMV_3C("3C","CMV","Calima Aviacion","Calima Aviacion","Spain"),
    APG_3D("3D","APG","Air People International","Air People International","Thailand"),
    GBQ_3G("3G","GBQ","Gambia Bird","Gambia Bird","Gambia"),
    AIE_3H("3H","AIE","Air Inuit","Air Inuit","Canada"),
    JSA_3K("3K","JSA","Jetstar Asia Airways","Jetstar Asia Airways","Singapore"),
    ISK_3L("3L","ISK","Intersky","Intersky","Austria"),
    GFT_3M("3M","GFT","Gulfstream International Airlines","Gulfstream International Airlines","USA"),
    URG_3N("3N","URG","Air Urga","Air Urga","Ukraine"),
    MAC_3O("3O","MAC","Air Arabia Maroc","Air Arabia Maroc","Morocco"),
    TNM_3P("3P","TNM","Tiara Air","Tiara Air","Aruba"),
    GAI_3R("3R","GAI","Moskovia Airlines","Moskovia Airlines","Russia"),
    AEN_3S("3S","AEN","Aeroland Airways","Aeroland Airways","Greece"),
    CAI_7H("7H","CAI","Corendon Airlines","Corendon Airlines","Turkey"),
    ERH_7H("7H","ERH","ERA Aviation","ERA Aviation","USA"),
    CSV_7I("7I","CSV","Coastal Travel Limited","Coastal Travel Limited","Tanzania"),
    INC_7I("7I","INC","Insel Air","Insel Air","Curacao"),
    TJK_7J("7J","TJK","Tajik Air","Tajik Air","Tajikistan"),
    KGL_7K("7K","KGL","Kolavia/Kogalymavia Airlines","Kolavia/Kogalymavia Airlines","Russia"),
    CRN_7L("7L","CRN","Aero Caribbean","Aero Caribbean","Cuba"),
    AAG_7M("7M","AAG","Air Atlantique","Air Atlantique","United Kingdom"),
    TOS_PM("PM","TOS","Tropic Air","Tropic Air","Belize"),
    CHB_PN("PN","CHB","China West Air","China West Air","China"),
    PAC_PO("PO","PAC","Polar Air Cargo","Polar Air Cargo","USA"),
    PJS_PP("PP","PJS","Jet Aviation Business Jets","Jet Aviation Business Jets","Switzerland"),
    TFK_PQ("PQ","TFK","Transafrik International","Transafrik International","Sao Tome and Principe"),
    PAL_PR("PR","PAL","Philippine Airlines","Philippine Airlines","Philippines"),
    AUI_PS("PS","AUI","Ukraine International Airlines","Ukraine International Airlines","Ukraine"),
    SWN_PT("PT","SWN","West Air Sweden","West Air Sweden","Sweden"),
    PNR_PV("PV","PNR","PAN Air Lineas Aereas","PAN Air Lineas Aereas","Spain"),
    PRF_PW("PW","PRF","Precision Air Services","Precision Air Services","Tanzania"),
    ANG_PX("PX","ANG","Air Niugini","Air Niugini","Papua New Guinea"),
    SLM_PY("PY","SLM","Surinam Airways","Surinam Airways","Suriname"),
    LAP_PZ("PZ","LAP","TAM Airlines/Transportes Aereos del Mercosur","TAM Airlines/Transportes Aereos del Mercosur","Paraguay"),
    DQA_Q2("Q2","DQA","Maldivian/Island Aviation Services","Maldivian/Island Aviation Services","Maldives"),
    MLA_Q5("Q5","MLA","40-Mile Air","40-Mile Air","USA"),
    CDP_Q6("Q6","CDP","Aero Condor","Aero Condor","Peru"),
    PEC_Q8("Q8","PEC","Pacific East Asia Cargo Airlines","Pacific East Asia Cargo Airlines","Philippines"),
    TSG_Q8("Q8","TSG","Trans Air Congo","Trans Air Congo","Congo"),
    CIM_QA("QA","CIM","Cimber","Cimber","Denmark"),
    GFG_QB("QB","GFG","SkyGeorgia","SkyGeorgia","Georgia"),
    QCL_QD("QD","QCL","Air Class Lineas Aereas","Air Class Lineas Aereas","Uruguay"),
    EAQ_QF("QF","EAQ","Eastern Australia Airlines","Eastern Australia Airlines","Australia"),
    QFA_QF("QF","QFA","Qantas Airways","Qantas Airways","Australia"),
    QLK_QF("QF","QLK","QantasLink","QantasLink","Australia"),
    QNZ_QF("QF","QNZ","JetConnect","JetConnect","New Zealand"),
    SSQ_QF("QF","SSQ","Sunstate Airlines","Sunstate Airlines","Australia"),
    LYN_QH("QH","LYN","Kyrgyzstan","Kyrgyzstan","Kyrgyzstan"),
    JZA_QK("QK","JZA","Jazz Aviation/Air Canada Express","Jazz Aviation/Air Canada Express","Canada"),
    LER_QL("QL","LER","LASER Linea Aerea de Servicio Ejecutivo Regional","LASER Linea Aerea de Servicio Ejecutivo Regional","Venezuela"),
    RNL_QL("QL","RNL","Aero Lanka/Serendib Express","Aero Lanka/Serendib Express","Sri Lanka"),
    AML_QM("QM","AML","Air Malawi","Air Malawi","Malawi"),
    ARR_QN("QN","ARR","Air Armenia","Air Armenia","Armenia"),
    UTY_QQ("QQ","UTY","Alliance Airlines","Alliance Airlines","Australia"),
    QTR_QR("QR","QTR","Qatar Airways","Qatar Airways","Qatar"),
    TVS_QS("QS","TVS","Travel Service/Smart Wings","Travel Service/Smart Wings","Czech Rep."),
    TPA_QT("QT","TPA","TAMPA Transportes Aereos Mercantiles Panamericanos","TAMPA Transportes Aereos Mercantiles Panamericanos","Colombia"),
    UGX_QU("QU","UGX","East African Airlines","East African Airlines","Uganda"),
    UTN_QU("QU","UTN","UTair-Ukraine","UTair-Ukraine","Ukraine"),
    LAO_QV("QV","LAO","Lao Airlines","Lao Airlines","Laos"),
    TCI_QW("QW","TCI","Turks Air Cargo","Turks Air Cargo","Turks and Caicos Islands"),
    QXE_QX("QX","QXE","Horizon Air","Horizon Air","USA"),
    BCS_QY("QY","BCS","European Air Transport","European Air Transport","Belgium"),
    AWQ_QZ("QZ","AWQ","Indonesia AirAsia","Indonesia AirAsia","Indonesia"),
    RPK_R0("R0","RPK","Royal Airlines","Royal Airlines","Pakistan"),
    ORB_R2("R2","ORB","Orenair/Orenburg Airlines","Orenair/Orenburg Airlines","Russia"),
    SYL_R3("R3","SYL","Yakutia Airlines","Yakutia Airlines","Russia"),
    JAV_R5("R5","JAV","Jordan Aviation","Jordan Aviation","Jordan"),
    DNU_R6("R6","DNU","DOT LT/Danu Oro Transportas","DOT LT/Danu Oro Transportas","Lithuania"),
    OCA_R7("R7","OCA","Aserca Airlines","Aserca Airlines","Venezuela"),
    CAM_R9("R9","CAM","Camai Air/Village Aviation","Camai Air/Village Aviation","USA"),
    RNA_RA("RA","RNA","Nepal Airlines","Nepal Airlines","Nepal"),
    SYR_RB("RB","SYR","Syrian Arab Airlines","Syrian Arab Airlines","Syrian Arab Rep."),
    FLI_RC("RC","FLI","Atlantic Airways","Atlantic Airways","Faroe Islands"),
    REA_RE("RE","REA","Stobart Air","Stobart Air","Ireland"),
    FWL_RF("RF","FWL","Florida West International Airways","Florida West International Airways","USA"),
    RPH_RH("RH","RPH","RPX Airlines/Republic Express Airlines","RPX Airlines/Republic Express Airlines","Indonesia"),
    RJA_RJ("RJ","RJA","Royal Jordanian","Royal Jordanian","Jordan"),
    RCT_RK("RK","RCT","R Airlines","R Airlines","Thailand"),
    ROT_RO("RO","ROT","Tarom Romanian Air Transport","Tarom Romanian Air Transport","Romania"),
    CHQ_RP("RP","CHQ","Chautauqua Airlines","Chautauqua Airlines","USA"),
    KMF_RQ("RQ","KMF","Kam Air","Kam Air","Afghanistan"),
    RFR_RR("RR","RFR","Royal Air Force","Royal Air Force","United Kingdom"),
    ORF_RS("RS","ORF","Oman Royal Flight","Oman Royal Flight","Oman"),
    SKV_RS("RS","SKV","Sky Regional Airlines/Air Canada Express","Sky Regional Airlines/Air Canada Express","Canada"),
    ABW_RU("RU","ABW","AirBridge Cargo Airlines","AirBridge Cargo Airlines","Russia"),
    CPN_RV("RV","CPN","Caspian Airlines Service Company","Caspian Airlines Service Company","Iran"),
    ROU_RV("RV","ROU","Air Canada Rouge","Air Canada Rouge","Canada"),
    RPA_RW("RW","RPA","Republic Airlines","Republic Airlines","USA"),
    LRS_RZ("RZ","LRS","SANSA Servicios Aereos Nacionales SA","SANSA Servicios Aereos Nacionales SA","Costa Rica"),
    BBR_S3("S3","BBR","Santa Barbara Airlines","Santa Barbara Airlines","Venezuela"),
    RZO_S4("S4","RZO","Sata International","Sata International","Portugal"),
    TCF_S5("S5","TCF","Shuttle America","Shuttle America","USA"),
    SRR_S6("S6","SRR","Star Air","Star Air","Denmark"),
    SBI_S7("S7","SBI","S7 Airlines/Siberia Airlines","S7 Airlines/Siberia Airlines","Russia"),
    SWW_S8("S8","SWW","Shovkoviy Shlyah Airlines","Shovkoviy Shlyah Airlines","Ukraine"),
    IKM_S9("S9","IKM","Starbow Airlines","Starbow Airlines","Ghana"),
    SAA_SA("SA","SAA","South African Airways","South African Airways","South Africa"),
    ACI_SB("SB","ACI","Aircalin/Air Caledonie International","Aircalin/Air Caledonie International","New Caledonia"),
    CDG_SC("SC","CDG","Shandong Airlines","Shandong Airlines","China"),
    SUD_SD("SD","SUD","Sudan Airways","Sudan Airways","Sudan"),
    XLF_SE("SE","XLF","XL Airways France","XL Airways France","France"),
    DTH_SF("SF","DTH","Tassili Airlines","Tassili Airlines","Algeria"),
    SEJ_SG("SG","SEJ","SpiceJet","SpiceJet","India"),
    AWS_SI("SI","AWS","Arab Wings","Arab Wings","Jordan"),
    BCI_SI("SI","BCI","Blue Islands","Blue Islands","United Kingdom"),
    SPA_SI("SI","SPA","Sierra Pacific Airlines","Sierra Pacific Airlines","USA"),
    EZD_Z2("Z2","EZD","Zest Airways","Zest Airways","Philippines"),
    SMJ_Z3("Z3","SMJ","AV Cargo","AV Cargo","Zimbabwe"),
    UDN_Z6("Z6","UDN","Dnieproavia","Dnieproavia","Ukraine"),
    AZN_Z8("Z8","AZN","Linea Aerea Amaszonas","Linea Aerea Amaszonas","Bolivia"),
    MTZ_Z8("Z8","MTZ","Mali Airways","Mali Airways","Mali"),
    DCP_Z9("Z9","DCP","Delta Connection Kenya","Delta Connection Kenya","Kenya"),
    SWM_ZA("ZA","SWM","Sky Wings Asia Airlines","Sky Wings Asia Airlines","Cambodia"),
    MON_ZB("ZB","MON","Monarch Airlines","Monarch Airlines","United Kingdom"),
    FDN_ZD("ZD","FDN","Dolphin Air","Dolphin Air","United Arab Emirates"),
    AZE_ZE("ZE","AZE","Arcus-Air Logistics","Arcus-Air Logistics","Germany"),
    ESR_ZE("ZE","ESR","Eastar Jet","Eastar Jet","Korea – Rep. of"),
    CSZ_ZH("ZH","CSZ","Shenzhen Airlines","Shenzhen Airlines","China"),
    AAF_ZI("ZI","AAF","Aigle Azur","Aigle Azur","France"),
    ARC_ZJ("ZJ","ARC","Air Routing International","Air Routing International","USA"),
    GLA_ZK("ZK","GLA","Great Lakes Aviation","Great Lakes Aviation","USA"),
    RXA_ZL("ZL","RXA","Regional Express","Regional Express","Australia"),
    CNB_ZM("ZM","CNB","CityLine Hungary","CityLine Hungary","Hungary"),
    NAY_ZN("ZN","NAY","NAYSA Navegacion y Servicios Aereos Canarios","NAYSA Navegacion y Servicios Aereos Canarios","Spain"),
    AZQ_ZP("ZP","AZQ","Silk Way Airlines","Silk Way Airlines","Azerbaijan"),
    LOC_ZQ("ZQ","LOC","Locair","Locair","USA"),
    AZS_ZR("ZR","AZS","Aviacon Zitotrans","Aviacon Zitotrans","Russia"),
    PUN_ZR("ZR","PUN","Punto Azul","Punto Azul","Equatorial Guinea"),
    AWC_ZT("ZT","AWC","Titan Airways","Titan Airways","United Kingdom"),
    AWI_ZW("ZW","AWI","Air Wisconsin","Air Wisconsin","USA"),
    GGN_ZX("ZX","GGN","Air Georgian/Air Alliance","Air Georgian/Air Alliance","Canada"),
    BOX_3S("3S","BOX","AeroLogic","AeroLogic","Germany"),
    GUY_3S("3S","GUY","Air Guyane Express/Air Antilles Express","Air Guyane Express/Air Antilles Express","French Guiana"),
    URN_3T("3T","URN","Turan Air","Turan Air","Azerbaijan"),
    CSC_3U("3U","CSC","Sichuan Airlines","Sichuan Airlines","China"),
    TAY_3V("3V","TAY","TNT Airways","TNT Airways","Belgium"),
    MWI_3W("3W","MWI","Malawian Airlines","Malawian Airlines","Malawi"),
    JAC_3X("3X","JAC","Japan Air Commuter","Japan Air Commuter","Japan"),
    XBO_3Y("3Y","XBO","Baseops International","Baseops International","USA"),
    TVP_3Z("3Z","TVP","Travel Service Polska","Travel Service Polska","Poland"),
    VTS_3Z("3Z","VTS","Everts Air/Tatonduk Outfitters","Everts Air/Tatonduk Outfitters","USA"),
    ZAW_3Z("3Z","ZAW","Zoom Airways","Zoom Airways","Bangladesh"),
    AGS_4A("4A","AGS","Air Go Airlines","Air Go Airlines","Greece"),
    AKL_4A("4A","AKL","Air Kiribati","Air Kiribati","Kiribati"),
    EYE_4A("4A","EYE","FS Air Service","FS Air Service","USA"),
    PAG_4B("4B","PAG","Perimeter Aviation","Perimeter Aviation","Canada"),
    ARE_4C("4C","ARE","Aires","Aires","Colombia"),
    CGK_4C("4C","CGK","Click Airways","Click Airways","United Arab Emirates"),
    ASD_4D("4D","ASD","Air Sinai","Air Sinai","Egypt"),
    GZP_4G("4G","GZP","Gazpromavia","Gazpromavia","Russia"),
    UBD_4H("4H","UBD","United Airways","United Airways","Bangladesh"),
    IZM_4I("4I","IZM","Izair","Izair","Turkey"),
    NWZ_4J("4J","NWZ","Nationwide Airlines Zambia","Nationwide Airlines Zambia","Zambia"),
    SMR_4J("4J","SMR","Somon Air","Somon Air","Tajikistan"),
    AAS_4K("4K","AAS","Askari Aviation","Askari Aviation","Pakistan"),
    KBA_4K("4K","KBA","Kenn Borek Air","Kenn Borek Air","Canada"),
    SGY_N5("N5","SGY","Skagway Air Service","Skagway Air Service","USA"),
    MUA_N8("N8","MUA","National Airlines","National Airlines","USA"),
    NVD_N9("N9","NVD","Avion Express","Avion Express","Lithuania"),
    NAO_NA("NA","NAO","North American Airlines","North American Airlines","USA"),
    NAC_NC("NC","NAC","Northern Air Cargo","Northern Air Cargo","USA"),
    NJS_NC("NC","NJS","Cobham Aviation Services Australia","Cobham Aviation Services Australia","Australia"),
    NMA_NE("NE","NMA","Nesma Airlines","Nesma Airlines","Egypt"),
    AVN_NF("NF","AVN","Air Vanuatu","Air Vanuatu","Vanuatu"),
    ANA_NH("NH","ANA","ANA All-Nippon Airways","ANA All-Nippon Airways","Japan"),
    PGA_NI("NI","PGA","Portugalia","Portugalia","Portugal"),
    NGB_NJ("NJ","NGB","Nordic Global Airlines","Nordic Global Airlines","Finland"),
    NKS_NK("NK","NKS","Spirit Airlines","Spirit Airlines","USA"),
    SAI_NL("NL","SAI","Shaheen Air International","Shaheen Air International","Pakistan"),
    NZM_NM("NM","NZM","Mount Cook Airline","Mount Cook Airline","New Zealand"),
    MOV_NN("NN","MOV","VIM Airlines","VIM Airlines","Russia"),
    NOS_NO("NO","NOS","Neos","Neos","Italy"),
    NIA_NP("NP","NIA","Nile Air","Nile Air","Egypt"),
    SKP_NP("NP","SKP","Skytrans Airlines","Skytrans Airlines","Australia"),
    AJX_NQ("NQ","AJX","Air Japan","Air Japan","Japan"),
    HBH_NS("NS","HBH","Hebei Airlines","Hebei Airlines","China"),
    IBB_NT("NT","IBB","Binter Canarias","Binter Canarias","Spain"),
    JTA_NU("NU","JTA","Japan Transocean Air","Japan Transocean Air","Japan"),
    AMU_NX("NX","AMU","Air Macau","Air Macau","Macau"),
    FNA_NY("NY","FNA","Air Iceland/Flugfelag Islands","Air Iceland/Flugfelag Islands","Iceland"),
    ANZ_NZ("NZ","ANZ","Air New Zealand","Air New Zealand","New Zealand"),
    AWK_NZ("NZ","AWK","Airwork","Airwork","New Zealand"),
    RLK_NZ("NZ","RLK","Air Nelson","Air Nelson","New Zealand"),
    JEA_O2("O2","JEA","OLT Jetair","OLT Jetair","Poland"),
    ABV_O4("O4","ABV","Antrak Air","Antrak Air","Ghana"),
    NOV_O9("O9","NOV","Nova Airline","Nova Airline","Sudan"),
    OAL_OA("OA","OAL","Olympic Air","Olympic Air","Greece"),
    BOV_OB("OB","BOV","Boliviana de Aviacion","Boliviana de Aviacion","Bolivia"),
    OAV_OC("OC","OAV","Omni Aviacao e Tecnologia/PGA Express","Omni Aviacao e Tecnologia/PGA Express","Portugal"),
    MXD_OD("OD","MXD","Malindo Air","Malindo Air","Malaysia"),
    ENT_OF("OF","ENT","Enter Air","Enter Air","Poland"),
    TML_OF("OF","TML","Transports et Travaux Aeriens de Madagascar","Transports et Travaux Aeriens de Madagascar","Madagascar"),
    FJM_OJ("OJ","FJM","Fly Jamaica Airways","Fly Jamaica Airways","Jamaica"),
    OLA_OJ("OJ","OLA","Overland Airways","Overland Airways","Nigeria"),
    CSA_OK("OK","CSA","Czech Airlines","Czech Airlines","Czech Rep."),
    MGL_OM("OM","MGL","MIAT Mongolian Airlines","MIAT Mongolian Airlines","Mongolia"),
    RON_ON("ON","RON","Our Airline","Our Airline","Nauru"),
    SKW_OO("OO","SKW","Skywest Airlines","Skywest Airlines","USA"),
    CQN_OQ("OQ","CQN","Chongqing Airlines","Chongqing Airlines","China"),
    CRF_OR("OR","CRF","Krym","Krym","Ukraine"),
    TFL_OR("OR","TFL","Arkefly","Arkefly","Netherlands"),
    AUA_OS("OS","AUA","Austrian Airlines","Austrian Airlines","Austria"),
    CTN_OU("OU","CTN","Croatia Airlines","Croatia Airlines","Croatia"),
    ELL_OV("OV","ELL","Estonian Air","Estonian Air","Estonia"),
    OVA_OV("OV","OVA","Melilla Airlines","Melilla Airlines","Spain"),
    OEA_OX("OX","OEA","Orient Thai Airlines","Orient Thai Airlines","Thailand"),
    ANS_OY("OY","ANS","Andes Lineas Aereas","Andes Lineas Aereas","Argentina"),
    OAE_OY("OY","OAE","Omni Air Express/Omni Air International","Omni Air Express/Omni Air International","USA"),
    AAR_OZ("OZ","AAR","Asiana Airlines","Asiana Airlines","Korea – Rep. of"),
    PFZ_P0("P0","PFZ","Proflight Commuter Services","Proflight Commuter Services","Zambia"),
    XAK_P2("P2","XAK","Airkenya Express","Airkenya Express","Kenya"),
    NSO_P4("P4","NSO","Aerolineas Sosa","Aerolineas Sosa","Honduras"),
    RPB_P5("P5","RPB","Copa Airlines Colombia","Copa Airlines Colombia","Colombia"),
    MUI_P6("P6","MUI","Trans Air","Trans Air","USA"),
    ESL_P7("P7","ESL","Russian Sky Airlines","Russian Sky Airlines","Russia"),
    PVN_P9("P9","PVN","Peruvian Airlines","Peruvian Airlines","Peru"),
    FCL_PA("PA","FCL","Florida Coastal Airlines","Florida Coastal Airlines","USA"),
    SPR_PB("PB","SPR","Provincial Airlines","Provincial Airlines","Canada"),
    PGT_PC("PC","PGT","Pegasus Airlines","Pegasus Airlines","Turkey"),
    POE_PD("PD","POE","Porter Airlines","Porter Airlines","Canada"),
    PEV_PE("PE","PEV","People’s Viennaline/Altenrhein Luftfahrt","People’s Viennaline/Altenrhein Luftfahrt","Austria"),
    PNW_PF("PF","PNW","Palestinian Airlines","Palestinian Airlines","Palestinian Territory"),
    BKP_PG("PG","BKP","Bangkok Airways","Bangkok Airways","Thailand"),
    PAO_PH("PH","PAO","Polynesian Airlines","Polynesian Airlines","Samoa"),
    SPM_PJ("PJ","SPM","Air Saint-Pierre","Air Saint-Pierre","St. Pierre and Miquelon"),
    PIA_PK("PK","PIA","Pakistan International Airlines","Pakistan International Airlines","Pakistan"),
    ARA_W3("W3","ARA","Arik Air","Arik Air","Nigeria"),
    DNU_W3("W3","DNU","Danu Oro Transportas","Danu Oro Transportas","Lithuania"),
    SWT_W3("W3","SWT","Swiftair","Swiftair","Spain"),
    BES_W4("W4","BES","Aero Services Executive","Aero Services Executive","France"),
    IRM_W5("W5","IRM","Mahan Air","Mahan Air","Iran"),
    WZZ_W6("W6","WZZ","Wizz Air","Wizz Air","Hungary"),
    CJT_W8("W8","CJT","CargoJet Airways","CargoJet Airways","Canada"),
    JAB_W9("W9","JAB","Air Bagan","Air Bagan","Myanmar"),
    KLC_WA("WA","KLC","KLM Cityhopper","KLM Cityhopper","Netherlands"),
    RWD_WB("WB","RWD","Rwandair Express","Rwandair Express","Rwanda"),
    ISV_WC("WC","ISV","Islena Airlines","Islena Airlines","Honduras"),
    CWC_WE("WE","CWC","Centurion Air Cargo","Centurion Air Cargo","USA"),
    WIF_WF("WF","WIF","Wideroe Flyveselskap","Wideroe Flyveselskap","Norway"),
    SWG_WG("WG","SWG","Sunwing Airlines","Sunwing Airlines","Canada"),
    TDX_WI("WI","TDX","TradeWinds Airlines","TradeWinds Airlines","USA"),
    LAL_WJ("WJ","LAL","Air Labrador","Air Labrador","Canada"),
    EDW_WK("WK","EDW","Edelweiss Air","Edelweiss Air","Switzerland"),
    WIA_WM("WM","WIA","Winair/Windward Islands Airways","Winair/Windward Islands Airways","Sint Maarten"),
    SWA_WN("WN","SWA","Southwest Airlines","Southwest Airlines","USA"),
    MKU_WP("WP","MKU","Island Air","Island Air","USA"),
    WEN_WR("WR","WEN","WestJet Encore","WestJet Encore","Canada"),
    WJA_WS("WS","WJA","WestJet","WestJet","Canada"),
    WSG_WT("WT","WSG","Wasaya Airways","Wasaya Airways","Canada"),
    WOW_WW("WW","WOW","WOW air","WOW air","Iceland"),
    BCY_WX("WX","BCY","CityJet","CityJet","Ireland"),
    OMA_WY("WY","OMA","Oman Air","Oman Air","Oman"),
    MDJ_WZ("WZ","MDJ","Jetran Air","Jetran Air","Romania"),
    VAZ_WZ("WZ","VAZ","Red Wings Airlines","Red Wings Airlines","Russia"),
    TUI_X3("X3","TUI","TUIfly","TUIfly","Germany"),
    OTJ_X5("X5","OTJ","Fly Romania","Fly Romania","Romania"),
    DAP_X8("X8","DAP","Aerovias DAP","Aerovias DAP","Chile"),
    KHO_X9("X9","KHO","Khors Aircompany","Khors Aircompany","Ukraine"),
    XAA_XA("XA","XAA","ARINC/Aeronautical Radio Inc.","ARINC/Aeronautical Radio Inc.","USA"),
    IAT_XB("XB","IAT","IATA/International Air Transport Association","IATA/International Air Transport Association","Canada"),
    KDC_XC("XC","KDC","KD Air","KD Air","Canada"),
    VLK_XF("XF","VLK","Vladivostok Air","Vladivostok Air","Russia"),
    KHH_XH("XH","KHH","Alexandria Airlines","Alexandria Airlines","Egypt"),
    XXH_XH("XH","XXH","Special Ground Handling Service","Special Ground Handling Service","USA"),
    XXI_XI("XI","XXI","AEROTEL/Aeronautical Telecommunications","AEROTEL/Aeronautical Telecommunications","Jamaica"),
    TAX_XJ("XJ","TAX","Thai AirAsia X","Thai AirAsia X","Thailand"),
    CCM_XK("XK","CCM","CCM Airlines/Compagnie Corse Mediterrannee","CCM Airlines/Compagnie Corse Mediterrannee","France"),
    LNE_XL("XL","LNE","LAN Ecuador","LAN Ecuador","Ecuador"),
    JLJ_XM("XM","JLJ","J-Air","J-Air","Japan"),
    JTE_XM("XM","JTE","JetEx/Australian Air Express","JetEx/Australian Air Express","Australia"),
    XAR_XN("XN","XAR","Xpress Air","Xpress Air","Indonesia"),
    SXS_XQ("XQ","SXS","SunExpress","SunExpress","Turkey"),
    OZW_XR("XR","OZW","SkyWest Airlines","SkyWest Airlines","Australia"),
    SIT_XS("XS","SIT","SITA","SITA","Belgium"),
    SKT_XT("XT","SKT","Sky Star Airways","Sky Star Airways","Thailand"),
    AXK_XU("XU","AXK","African Express Airways","African Express Airways","Kenya"),
    KNE_XY("XY","KNE","Nas Air/Al-Khayala Airline","Nas Air/Al-Khayala Airline","Saudi Arabia"),
    EXY_XZ("XZ","EXY","South African Express Airways","South African Express Airways","South Africa"),
    VOI_Y4("Y4","VOI","Volaris","Volaris","Mexico"),
    AWA_Y5("Y5","AWA","Asia Wings","Asia Wings","Kazakhstan"),
    GMR_Y5("Y5","GMR","Golden Myanmar Airlines","Golden Myanmar Airlines","Myanmar"),
    TYA_Y7("Y7","TYA","Taimyr Air Company","Taimyr Air Company","Russia"),
    YZR_Y8("Y8","YZR","Yangtze River Express Airlines","Yangtze River Express Airlines","China"),
    IRK_Y9("Y9","IRK","Kish Air","Kish Air","Iran"),
    LLM_YC("YC","LLM","Yamal Airlines","Yamal Airlines","Russia"),
    CFC_YF("YF","CFC","Canadian Armed Forces","Canadian Armed Forces","Canada"),
    OTL_YG("YG","OTL","South Airlines","South Airlines","Ukraine"),
    RSI_YI("YI","RSI","Air Sunshine","Air Sunshine","USA"),
    NTN_YJ("YJ","NTN","National Airways","National Airways","South Africa"),
    BSA_YL("YL","BSA","Air Bissau International","Air Bissau International","Guinea-Bissau"),
    ULG_YL("YL","ULG","U Airlines","U Airlines","Thailand"),
    MGX_YM("YM","MGX","Montenegro Airlines","Montenegro Airlines","Montenegro"),
    CRQ_YN("YN","CRQ","Air Creebec","Air Creebec","Canada"),
    MCM_YO("YO","MCM","Heli Air Monaco","Heli Air Monaco","Monaco"),
    POT_YQ("YQ","POT","Polet Cargo Airlines","Polet Cargo Airlines","Russia"),
    EGJ_YR("YR","EGJ","Scenic Airlines","Scenic Airlines","USA"),
    ASH_YV("YV","ASH","Mesa Airlines","Mesa Airlines","USA"),
    ANE_YW("YW","ANE","Air Nostrum","Air Nostrum","Spain"),
    MAU_MK("MK","MAU","Air Mauritius","Air Mauritius","Mauritius"),
    BIE_ML("ML","BIE","Air Mediterranee","Air Mediterranee","France"),
    ETC_ML("ML","ETC","ATTICO African Transport Trading and Investment Co.","ATTICO African Transport Trading and Investment Co.","Sudan"),
    APJ_MM("MM","APJ","Peach Aviation","Peach Aviation","Japan"),
    MMZ_MM("MM","MMZ","euroAtlantic airways","euroAtlantic airways","Portugal"),
    CAW_MN("MN","CAW","kulula.com/Comair Commercial Airlines","kulula.com/Comair Commercial Airlines","South Africa"),
    AUH_MO("MO","AUH","Abu Dhabi Amiri Flight","Abu Dhabi Amiri Flight","United Arab Emirates"),
    CAV_MO("MO","CAV","Calm Air","Calm Air","Canada"),
    MPH_MP("MP","MPH","Martinair","Martinair","Netherlands"),
    ENY_MQ("MQ","ENY","Envoy Air/American Eagle","Envoy Air/American Eagle","USA"),
    MML_MR("MR","MML","Hunnu Air","Hunnu Air","Mongolia"),
    MSE_MS("MS","MSE","EgyptAir Express","EgyptAir Express","Egypt"),
    MSR_MS("MS","MSR","EgyptAir","EgyptAir","Egypt"),
    TCX_MT("MT","TCX","Thomas Cook Airlines","Thomas Cook Airlines","United Kingdom"),
    CES_MU("MU","CES","China Eastern Airlines","China Eastern Airlines","China"),
    BUG_MW("MW","BUG","Mokulele Airlines","Mokulele Airlines","USA"),
    MYD_MW("MW","MYD","Maya Island Air","Maya Island Air","Belize"),
    MWA_MY("MY","MWA","Midwest Airlines","Midwest Airlines","Egypt"),
    MNA_MZ("MZ","MNA","Merpati Nusantara Airlines","Merpati Nusantara Airlines","Indonesia"),
    QNK_N2("N2","QNK","Kabo Air","Kabo Air","Nigeria"),
    NWS_N4("N4","NWS","Nordwind Airlines","Nordwind Airlines","Russia"),
    TNB_N4("N4","TNB","Trans Air Benin","Trans Air Benin","Benin"),
    MDM_N5("N5","MDM","Medavia","Medavia","Malta"),
    CGL_SJ("SJ","CGL","Seagle Air","Seagle Air","Slovakia"),
    SAS_SK("SK","SAS","SAS Scandinavian Airlines System","SAS Scandinavian Airlines System","Denmark/Norway/Sweden"),
    TLM_SL("SL","TLM","Thai Lion Air","Thai Lion Air","Thailand"),
    MNP_SM("SM","MNP","Spirit of Manila Airlines","Spirit of Manila Airlines","Philippines"),
    BEL_SN("SN","BEL","Brussels Airlines","Brussels Airlines","Belgium"),
    HKA_SO("SO","HKA","Superior Aviation","Superior Aviation","USA"),
    SLC_SO("SO","SLC","SALSA d’Haiti","SALSA d’Haiti","Haiti"),
    SAT_SP("SP","SAT","SATA Air Acores","SATA Air Acores","Portugal"),
    SIA_SQ("SQ","SIA","Singapore Airlines","Singapore Airlines","Singapore"),
    SQC_SQ("SQ","SQC","Singapore Airlines Cargo","Singapore Airlines Cargo","Singapore"),
    CRL_SS("SS","CRL","Corsairfly","Corsairfly","France"),
    GMI_ST("ST","GMI","Germania","Germania","Germany"),
    AFL_SU("SU","AFL","Aeroflot Russian Airlines","Aeroflot Russian Airlines","Russia"),
    SVA_SV("SV","SVA","Saudi Arabian Airlines","Saudi Arabian Airlines","Saudi Arabia"),
    NMB_SW("SW","NMB","Air Namibia","Air Namibia","Namibia"),
    SCX_SY("SY","SCX","Sun Country Airlines","Sun Country Airlines","USA"),
    TPU_T0("T0","TPU","Taca Peru","Taca Peru","Peru"),
    TMA_T2("T2","TMA","Trans Mediterranean Airways","Trans Mediterranean Airways","Lebanon"),
    EZE_T3("T3","EZE","Eastern Airways","Eastern Airways","United Kingdom"),
    TUA_T5("T5","TUA","Turkmenistan Airlines","Turkmenistan Airlines","Turkmenistan"),
    TVR_T6("T6","TVR","Tavrey Airlines/Tavria Aviakompania","Tavrey Airlines/Tavria Aviakompania","Ukraine"),
    TJT_T7("T7","TJT","Twin Jet","Twin Jet","France"),
    TAI_TA("TA","TAI","Taca International Airlines","Taca International Airlines","El Salvador"),
    JAF_TB("TB","JAF","Jetairfly","Jetairfly","Belgium"),
    ATC_TC("TC","ATC","Air Tanzania","Air Tanzania","Tanzania"),
    LUR_TD("TD","LUR","Atlantis European Airways","Atlantis European Airways","Armenia"),
    SCW_TF("TF","SCW","Malmo Aviation","Malmo Aviation","Sweden"),
    THA_TG("TG","THA","Thai Airways International","Thai Airways International","Thailand"),
    TSE_TH("TH","TSE","Transmile Air Services","Transmile Air Services","Malaysia"),
    TOL_TI("TI","TOL","TolAir Services","TolAir Services","Puerto Rico"),
    AJA_THY("THY","AJA","AnadoluJet","AnadoluJet","Turkey"),
    THY_TK("TK","THY","Turkish Airlines","Turkish Airlines","Turkey"),
    ANO_TL("TL","ANO","Airnorth Regional","Airnorth Regional","Australia"),
    LAM_TM("TM","LAM","LAM","LAM","Mozambique"),
    THT_TN("TN","THT","Air Tahiti Nui","Air Tahiti Nui","French Polynesia"),
    TVF_TO("TO","TVF","Transavia France","Transavia France","France"),
    TDM_TQ("TQ","TDM","Tandem Aereo","Tandem Aereo","Moldova"),
    TGW_TR("TR","TGW","Tiger Airways","Tiger Airways","Singapore"),
    TSC_TS("TS","TSC","Air Transat","Air Transat","Canada"),
    TGW_TT("TT","TGW","Tiger Airways Australia","Tiger Airways Australia","Australia"),
    TAR_TU("TU","TAR","Tunisair","Tunisair","Tunisia"),
    TBA_TV("TV","TBA","Tibet Airlines","Tibet Airlines","China"),
    FWI_TX("TX","FWI","Air Caraibes","Air Caraibes","Guadeloupe/Martinique"),
    TPC_TY("TY","TPC","Air Caledonie","Air Caledonie","New Caledonia"),
    SCO_TZ("TZ","SCO","Scoot","Scoot","Singapore"),
    TWG_TZ("TZ","TWG","Air-taxi europe","Air-taxi europe","Germany"),
    EZY_U2("U2","EZY","easyJet","easyJet","United Kingdom"),
    AIA_U3("U3","AIA","Avies","Avies","Estonia"),
    SVR_U6("U6","SVR","Ural Airlines","Ural Airlines","Russia"),
    UGA_U7("U7","UGA","Air Uganda","Air Uganda","Uganda"),
    UAL_UA("UA","UAL","United Airlines","United Airlines","USA"),
    UBA_UB("UB","UBA","Myanma Airways","Myanma Airways","Myanmar"),
    LCO_UC("UC","LCO","LAN Cargo","LAN Cargo","Chile"),
    HER_UD("UD","HER","Hex’Air","Hex’Air","France"),
    NAS_UE("UE","NAS","Nasair","Nasair","Eritrea"),
    UKM_UF("UF","UKM","UM Air/Ukrainian Mediterranean Airlines","UM Air/Ukrainian Mediterranean Airlines","Ukraine"),
    SEN_UG("UG","SEN","Sevenair","Sevenair","Tunisia"),
    GMT_UJ("UJ","GMT","Magnicharters","Magnicharters","Mexico"),
    LMU_UJ("UJ","LMU","AlMasria Universal Airlines","AlMasria Universal Airlines","Egypt"),
    ALK_UL("UL","ALK","SriLankan Airlines","SriLankan Airlines","Sri Lanka"),
    TSO_UN("UN","TSO","Transaero Airlines","Transaero Airlines","Russia"),
    HKE_UO("UO","HKE","Hong Kong Express","Hong Kong Express","Hong Kong"),
    BHS_UP("UP","BHS","Bahamasair","Bahamasair","Bahamas"),
    KMV_UR("UR","KMV","UTair Express","UTair Express","Russia"),
    AWE_US("US","AWE","US Airways","US Airways","USA"),
    JIA_US("US","JIA","PSA Airlines","PSA Airlines","USA"),
    PDT_US("US","PDT","Piedmont Airlines","Piedmont Airlines","USA"),
    UTA_UT("UT","UTA","UTair Aviation","UTair Aviation","Russia"),
    REU_UU("UU","REU","Air Austral","Air Austral","Reunion Island"),
    UTP_UW("UW","UTP","Uni-Top Airlines","Uni-Top Airlines","China"),
    AEA_UX("UX","AEA","Air Europa","Air Europa","Spain"),
    BRQ_UZ("UZ","BRQ","Buraq Air Transport","Buraq Air Transport","Libya"),
    VCV_V0("V0","VCV","Conviasa","Conviasa","Venezuela"),
    RBY_V2("V2","RBY","Vision Airlines","Vision Airlines","USA"),
    KRP_V3("V3","KRP","Carpatair","Carpatair","Romania"),
    VEC_V4("V4","VEC","Vensecar Internacional","Vensecar Internacional","Venezuela"),
    VOG_V6("V6","VOG","Voyager Airlines","Voyager Airlines","Bangladesh"),
    VOE_V7("V7","VOE","Volotea","Volotea","Spain"),
    TPS_V8("V8","TPS","TAPSA Transportes Aereos Petroleros SA","TAPSA Transportes Aereos Petroleros SA","Argentina"),
    VAS_V8("V8","VAS","ATRAN Aviatrans Cargo Airlines","ATRAN Aviatrans Cargo Airlines","Russia"),
    VAU_VA("VA","VAU","Virgin Australia International Airlines","Virgin Australia International Airlines","Australia"),
    VIV_VB("VB","VIV","Viva Aerobus","Viva Aerobus","Mexico"),
    VAL_VC("VC","VAL","Voyageur Airways","Voyageur Airways","Canada"),
    KPA_VD("VD","KPA","Henan Airlines","Henan Airlines","China"),
    VJC_VD("VD","VJC","VietJet Air","VietJet Air","Vietnam"),
    VLU_VF("VF","VLU","Valuair","Valuair","Singapore"),
    VLM_VG("VG","VLM","VLM","VLM","Belgium"),
    ALV_VH("VH","ALV","Aeropostal Alas de Venezuela","Aeropostal Alas de Venezuela","Venezuela"),
    VDA_VI("VI","VDA","Volga-Dnepr Airlines","Volga-Dnepr Airlines","Russia"),
    VES_VI("VI","VES","Vieques Air Link","Vieques Air Link","Puerto Rico"),
    VIM_VL("VL","VIM","Air VIA Bulgarian Airways","Air VIA Bulgarian Airways","Bulgaria"),
    HVN_VN("VN","HVN","Vietnam Airlines","Vietnam Airlines","Vietnam"),
    TYR_VO("VO","TYR","Tyrolean Airways/Austrian Arrows","Tyrolean Airways/Austrian Arrows","Austria"),
    TCV_VR("VR","TCV","TACV Cabo Verde Airlines","TACV Cabo Verde Airlines","Cape Verde"),
    VIR_VS("VS","VIR","Virgin Atlantic Airways","Virgin Atlantic Airways","United Kingdom"),
    VTA_VT("VT","VTA","Air Tahiti","Air Tahiti","French Polynesia"),
    TAO_VW("VW","TAO","Transportes Aeromar","Transportes Aeromar","Mexico"),
    VRD_VX("VX","VRD","Virgin America","Virgin America","USA"),
    VLG_VY("VY","VLG","Vueling Airlines","Vueling Airlines","Spain"),
    WDL_W1("W1","WDL","WDL Aviation","WDL Aviation","Germany"),
    MJX_4L("4L","MJX","Euroline","Euroline","Georgia"),
    DSM_4M("4M","DSM","LAN Argentina","LAN Argentina","Argentina"),
    ANT_4N("4N","ANT","Air North Charter","Air North Charter","Canada"),
    AIJ_4O("4O","AIJ","Interjet/ABC Aerolineas","Interjet/ABC Aerolineas","Mexico"),
    SBO_4P("4P","SBO","Stabo Air","Stabo Air","Zambia"),
    SFW_4Q("4Q","SFW","Safi Airways","Safi Airways","United Arab Emirates"),
    NTA_4R("4R","NTA","Northern Thunderbird Air","Northern Thunderbird Air","Canada"),
    BHP_4T("4T","BHP","Belair Airlines","Belair Airlines","Switzerland"),
    GWI_4U("4U","GWI","Germanwings","Germanwings","Germany"),
    AJK_4W("4W","AJK","Allied Air Cargo","Allied Air Cargo","Nigeria"),
    WAV_4W("4W","WAV","Warbelow’s Air Ventures","Warbelow’s Air Ventures","USA"),
    MEC_4X("4X","MEC","Air Mercury/Mercury Air Cargo","Air Mercury/Mercury Air Cargo","USA"),
    TUD_4Y("4Y","TUD","Flight Alaska","Flight Alaska","USA"),
    LNK_4Z("4Z","LNK","Airlink","Airlink","South Africa"),
    CLH_CL("CL","CLH","Lufthansa Cityline","Lufthansa Cityline","Germany"),
    AIP_5A("5A","AIP","Alpine Air Express","Alpine Air Express","USA"),
    EAK_5B("5B","EAK","Euro Asia Air International","Euro Asia Air International","Kazakhstan"),
    NCH_5B("5B","NCH","Chanchangi Airlines Nigeria","Chanchangi Airlines Nigeria","Nigeria"),
    ICL_5C("5C","ICL","CAL Cargo Air Lines/Cavei Avir Levitanim","CAL Cargo Air Lines/Cavei Avir Levitanim","Israel"),
    NRR_5C("5C","NRR","Nature Air","Nature Air","Costa Rica"),
    SLI_5D("5D","SLI","Aeromexico Connect","Aeromexico Connect","Mexico"),
    EKA_5E("5E","EKA","Equaflight Service","Equaflight Service","Congo"),
    FFV_5H("5H","FFV","Fly540/Five Forty Aviation","Fly540/Five Forty Aviation","Kenya"),
    CEB_5J("5J","CEB","Cebu Pacific Air","Cebu Pacific Air","Philippines"),
    HFY_5K("5K","HFY","Hifly","Hifly","Portugal"),
    CFS_EM("EM","CFS","Empire Airlines","Empire Airlines","USA"),
    DLA_EN("EN","DLA","Air Dolomiti","Air Dolomiti","Italy"),
    LHN_EO("EO","LHN","Express One International","Express One International","USA"),
    IRC_EP("EP","IRC","Iran Asseman Airlines","Iran Asseman Airlines","Iran"),
    TAE_EQ("EQ","TAE","TAME","TAME","Ecuador"),
    DHX_ES("ES","DHX","SNAS/DHL/DHL International Aviation ME","SNAS/DHL/DHL International Aviation ME","Bahrain"),
    ETH_ET("ET","ETH","Ethiopian Airlines","Ethiopian Airlines","Ethiopia"),
    UEA_EU("EU","UEA","Chengdu Airlines","Chengdu Airlines","China"),
    ASQ_EV("EV","ASQ","ExpressJet Airlines","ExpressJet Airlines","USA"),
    EWG_EW("EW","EWG","Eurowings","Eurowings","Germany"),
    BJK_EX("EX","BJK","Atlantic Airlines","Atlantic Airlines","USA"),
    EFL_EY("EY","EFL","Eagle Air","Eagle Air","Tanzania"),
    ETD_EY("EY","ETD","Etihad Airways","Etihad Airways","United Arab Emirates"),
    EIA_EZ("EZ","EIA","Evergreen International Airlines","Evergreen International Airlines","USA"),
    SUS_EZ("EZ","SUS","Sun Air of Scandinavia","Sun Air of Scandinavia","Denmark"),
    FSW_F3("F3","FSW","Faso Airways","Faso Airways","Burkina Faso"),
    FXL_F3("F3","FXL","Fly Excellent","Fly Excellent","Sweden"),
    SGB_F3("F3","SGB","Sky King","Sky King","USA"),
    DWT_F7("F7","DWT","Darwin Airline/Etihad Regional","Darwin Airline/Etihad Regional","Switzerland"),
    VRE_F7("F7","VRE","Volare Airlines","Volare Airlines","Ukraine"),
    FFT_F9("F9","FFT","Frontier Airlines","Frontier Airlines","USA"),
    SFR_FA("FA","SFR","Safair/FlySafair","Safair/FlySafair","South Africa"),
    LZB_FB("FB","LZB","Bulgaria Air","Bulgaria Air","Bulgaria"),
    FCX_FC("FC","FCX","Falcon Express Cargo Airlines","Falcon Express Cargo Airlines","United Arab Emirates"),
    AIQ_FD("FD","AIQ","Thai AirAsia","Thai AirAsia","Thailand"),
    AFG_FG("FG","AFG","Ariana Afghan Airlines","Ariana Afghan Airlines","Afghanistan"),
    ICE_FI("FI","ICE","Icelandair","Icelandair","Iceland"),
    FJI_FJ("FJ","FJI","Fiji Airways","Fiji Airways","Fiji"),
    AXB_IX("IX","AXB","Air India Express","Air India Express","India"),
    IYE_IY("IY","IYE","Yemenia","Yemenia","Yemen"),
    AIZ_IZ("IZ","AIZ","Arkia","Arkia","Israel"),
    AHC_J2("J2","AHC","AZAL Avia Cargo","AZAL Avia Cargo","Azerbaijan"),
    AHY_J2("J2","AHY","AZAL Azerbaijan Airlines/AHY","AZAL Azerbaijan Airlines/AHY","Azerbaijan"),
    PLR_J3("J3","PLR","Northwestern Air","Northwestern Air","Canada"),
    BFL_J4("J4","BFL","Buffalo Airways","Buffalo Airways","Canada"),
    EPA_J5("J5","EPA","Shenzhen Donghai Airlines","Shenzhen Donghai Airlines","China"),
    ARW_J6("J6","ARW","Jamaica Air Shuttle","Jamaica Air Shuttle","Jamaica"),
    DNM_J7("J7","DNM","Denim Air","Denim Air","Netherlands"),
    BVT_J8("J8","BVT","Berjaya Air","Berjaya Air","Malaysia"),
    JZR_J9("J9","JZR","Jazeera Airways","Jazeera Airways","Kuwait"),
    BON_JA("JA","BON","B & H Airlines","B & H Airlines","Bosnia-Herzegovina"),
    JGN_JA("JA","JGN","Jagson Airlines","Jagson Airlines","India"),
    JBA_JB("JB","JBA","Helijet International","Helijet International","Canada"),
    JEX_JC("JC","JEX","JAL Express","JAL Express","Japan"),
    MNO_JE("JE","MNO","Mango","Mango","South Africa"),
    LAB_JF("JF","LAB","LAB Flying Service","LAB Flying Service","USA"),
    FDA_JH("JH","FDA","Fuji Dream Airlines","Fuji Dream Airlines","Japan"),
    AGX_JJ("JJ","AGX","Aviogenex","Aviogenex","Serbia"),
    JAL_JL("JL","JAL","Japan Airlines","Japan Airlines","Japan"),
    JKT_JM("JM","JKT","Jetstar Hong Kong","Jetstar Hong Kong","Italy"),
    NLV_JN("JN","NLV","Livingston Compagnia Aerea","Livingston Compagnia Aerea","Italy"),
    ADR_JP("JP","ADR","Adria Airways","Adria Airways","Slovenia"),
    JST_JQ("JQ","JST","Jetstar Airways","Jetstar Airways","Australia"),
    LAV_JQ("JQ","LAV","AlbaStar","AlbaStar","Spain"),
    JOY_JR("JR","JOY","Joy Air","Joy Air","China"),
    KOR_JS("JS","KOR","Air Koryo","Air Koryo","Korea – Dem. People’s Rep."),
    LNI_JT("JT","LNI","Lion Airlines/Lion Mentari Air","Lion Airlines/Lion Mentari Air","Indonesia"),
    JAT_JU("JU","JAT","Jat Airways","Jat Airways","Serbia"),
    BLS_JV("JV","BLS","Bearskin Airlines","Bearskin Airlines","Canada"),
    VNL_JW("JW","VNL","Vanilla Air","Vanilla Air","Japan"),
    IWY_JZ("JZ","IWY","Air Turks and Caicos","Air Turks and Caicos","Turks and Caicos Islands"),
    ELO_K2("K2","ELO","EuroLOT","EuroLOT","Poland"),
    CKS_K4("K4","CKS","Kalitta Air","Kalitta Air","USA"),
    ABE_K5("K5","ABE","Aban Air","Aban Air","Iran"),
    SQH_K5("K5","SQH","Wings of Alaska/SeaPort Airlines","Wings of Alaska/SeaPort Airlines","USA"),
    KHV_K6("K6","KHV","Cambodia Angkor Air","Cambodia Angkor Air","Cambodia"),
    ZAK_K8("K8","ZAK","Zambia Skyways","Zambia Skyways","Zambia"),
    ESD_K9("K9","ESD","Esen Air","Esen Air","Kyrgyzstan"),
    KFS_K9("K9","KFS","Kalitta Charters","Kalitta Charters","USA"),
    KRI_K9("K9","KRI","Krylo Aviakompania","Krylo Aviakompania","Russia"),
    HDA_KA("KA","HDA","Dragonair/Hong Kong Dragon Airlines","Dragonair/Hong Kong Dragon Airlines","Hong Kong"),
    DRK_KB("KB","DRK","Druk Air","Druk Air","Bhutan"),
    KZR_KC("KC","KZR","Air Astana","Air Astana","Kazakhstan"),
    KAL_KE("KE","KAL","Korean Air","Korean Air","Korea – Rep. of"),
    BLF_KF("KF","BLF","Blue1","Blue1","Finland"),
    GTV_KG("KG","GTV","Aerogaviota","Aerogaviota","Cuba"),
    AAH_KH("KH","AAH","Aloha Air Cargo","Aloha Air Cargo","USA"),
    KKK_KK("KK","KKK","AtlasJet","AtlasJet","Turkey"),
    KLM_KL("KL","KLM","KLM Royal Dutch Airlines","KLM Royal Dutch Airlines","Netherlands"),
    AMC_KM("KM","AMC","Air Malta","Air Malta","Malta"),
    CUA_KN("KN","CUA","China United Airlines","China United Airlines","China"),
    AER_KO("KO","AER","Alaska Central Express","Alaska Central Express","USA"),
    QNK_KO("KO","QNK","Kabo Air","Kabo Air","Nigeria"),
    KQA_KQ("KQ","KQA","Kenya Airways","Kenya Airways","Kenya"),
    KMZ_KR("KR","KMZ","Comores Aviation","Comores Aviation","Comoros"),
    PEN_KS("KS","PEN","Penair/Peninsula Airways","Penair/Peninsula Airways","USA"),
    KAC_KU("KU","KAC","Kuwait Airways","Kuwait Airways","Kuwait"),
    KFA_KW("KW","KFA","Kelowna Flightcraft Air Charter","Kelowna Flightcraft Air Charter","Canada"),
    CAY_KX("KX","CAY","Cayman Airways","Cayman Airways","Cayman Islands"),
    NCA_KZ("KZ","NCA","Nippon Cargo Airlines","Nippon Cargo Airlines","Japan"),
    LYC_L2("L2","LYC","Lynden Air Cargo","Lynden Air Cargo","USA"),
    JOS_L3("L3","JOS","DHL de Guatemala","DHL de Guatemala","Guatemala"),
    LTR_L5("L5","LTR","Lufttransport","Lufttransport","Norway"),
    MAI_L6("L6","MAI","Mauritanian Airlines International","Mauritanian Airlines International","Mauritania"),
    VNZ_L6("L6","VNZ","TAM Air/Tbilaviamsheni","TAM Air/Tbilaviamsheni","Georgia"),
    LHS_L7("L7","LHS","Lugansk Airlines","Lugansk Airlines","Ukraine"),
    LAN_LA("LA","LAN","LAN Airlines","LAN Airlines","Chile"),
    LBR_LB("LB","LBR","Air Costa","Air Costa","India"),
    LOG_LC("LC","LOG","Loganair","Loganair","United Kingdom"),
    AHK_LD("LD","AHK","Air Hong Kong","Air Hong Kong","Hong Kong"),
    TUY_LD("LD","TUY","Linea Turistica Aerotuy","Linea Turistica Aerotuy","Venezuela"),
    LGL_LG("LG","LGL","Luxair","Luxair","Luxembourg"),
    GEC_LH("LH","GEC","Lufthansa Cargo","Lufthansa Cargo","Germany"),
    LIA_LI("LI","LIA","LIAT","LIAT","Antigua and Barbuda"),
    JNA_LJ("LJ","JNA","Jin Air","Jin Air","Korea – Rep. of"),
    SLA_LJ("LJ","SLA","Sierra National Airlines","Sierra National Airlines","Sierra Leone"),
    BSK_LL("LL","BSK","Miami Air International","Miami Air International","USA"),
    LAA_LN("LN","LAA","Lybian Arab Airlines","Lybian Arab Airlines","Libya"),
    LOT_LO("LO","LOT","LOT Polish Airlines","LOT Polish Airlines","Poland"),
    LPE_LP("LP","LPE","LAN Peru","LAN Peru","Peru"),
    LAQ_LQ("LQ","LAQ","Lebanese Air Transport","Lebanese Air Transport","Lebanon"),
    LRC_LR("LR","LRC","Lacsa","Lacsa","Costa Rica"),
    EXS_LS("LS","EXS","Jet2.com","Jet2.com","United Kingdom"),
    LTU_LT("LT","LTU","Air Lituanica","Air Lituanica","Lithuania"),
    LXP_LU("LU","LXP","Lan Express","Lan Express","Chile"),
    NMI_LW("LW","NMI","Pacific Wings/GeorgiaSkies/New Mexico Airlines","Pacific Wings/GeorgiaSkies/New Mexico Airlines","USA"),
    SWR_LX("LX","SWR","Swiss International Air Lines","Swiss International Air Lines","Switzerland"),
    SWU_LX("LX","SWU","Swiss European Air Lines","Swiss European Air Lines","Switzerland"),
    ELY_LY("LY","ELY","El Al","El Al","Israel"),
    MNG_M0("M0","MNG","Aero Mongolia","Aero Mongolia","Mongolia"),
    MZS_M2("M2","MZS","Mahfooz Aviation","Mahfooz Aviation","Gambia"),
    NFA_M3("M3","NFA","Air Norway/North Flying","Air Norway/North Flying","Denmark"),
    AJT_M6("M6","AJT","Amerijet International","Amerijet International","USA"),
    MAA_M7("M7","MAA","MasAir","MasAir","Mexico"),
    MSL_M7("M7","MSL","Marsland Aviation","Marsland Aviation","Sudan"),
    MSI_M9("M9","MSI","Motor Sich Aviakompania","Motor Sich Aviakompania","Ukraine"),
    MNB_MB("MB","MNB","MNG Airlines","MNG Airlines","Turkey"),
    MSC_MC("MC","MSC","Air Cairo","Air Cairo","Egypt"),
    RCH_MC("MC","RCH","Air Mobility Command","Air Mobility Command","USA"),
    MDG_MD("MD","MDG","Air Madagascar","Air Madagascar","Madagascar"),
    MEA_ME("ME","MEA","MEA Middle East Airlines Airliban","MEA Middle East Airlines Airliban","Lebanon"),
    CXA_MF("MF","CXA","Xiamen Airlines","Xiamen Airlines","China"),
    MIX_MG("MG","MIX","Midex Airlines","Midex Airlines","United Arab Emirates"),
    MAS_MH("MH","MAS","Malaysia Airlines","Malaysia Airlines","Malaysia"),
    MWG_MH("MH","MWG","MASwings","MASwings","Malaysia"),
    SLK_MI("MI","SLK","SilkAir","SilkAir","Singapore"),
    MLR_MJ("MJ","MLR","Mihin Lanka","Mihin Lanka","Sri Lanka"),
    ODS_5K("5K","ODS","Odessa Airlines","Odessa Airlines","Ukraine"),
    HFM_5M("5M","HFM","Hi Fly Malta","Hi Fly Malta","Malta"),
    MEG_5M("5M","MEG","Mega Maldives","Mega Maldives","Maldives"),
    AUL_5N("5N","AUL","Nordavia","Nordavia","Russia"),
    FPO_5O("5O","FPO","Europe Airpost","Europe Airpost","France"),
    BQB_5Q("5Q","BQB","BQB Lineas Aereas","BQB Lineas Aereas","Uruguay"),
    KAJ_5R("5R","KAJ","Karthago Airlines","Karthago Airlines","Tunisia"),
    PSV_5S("5S","PSV","Servicios Aereos Profesionales","Servicios Aereos Profesionales","Dominican Rep."),
    MPE_5T("5T","MPE","Canadian North","Canadian North","Canada"),
    CHG_5U("5U","CHG","Challenge Aero","Challenge Aero","Ukraine"),
    LDE_5U("5U","LDE","LADE Lineas Aereas del Estado","LADE Lineas Aereas del Estado","Argentina"),
    UKW_5V("5V","UKW","Lviv Airlines/Lvov Airlines","Lviv Airlines/Lvov Airlines","Ukraine"),
    UPS_5X("5X","UPS","UPS Airlines/United Parcel Service","UPS Airlines/United Parcel Service","USA"),
    GTI_5Y("5Y","GTI","Atlas Air","Atlas Air","USA"),
    IOS_5Y("5Y","IOS","Isles of Scilly Skybus","Isles of Scilly Skybus","United Kingdom"),
    BML_5Z("5Z","BML","Bismillah Airlines","Bismillah Airlines","Bangladesh"),
    BLX_6B("6B","BLX","TUIfly Nordic","TUIfly Nordic","Sweden"),
    PAS_6D("6D","PAS","Pelita Air Service","Pelita Air Service","Indonesia"),
    IGO_6E("6E","IGO","IndiGo Airlines","IndiGo Airlines","India"),
    FAO_6F("6F","FAO","Falcon Air Express","Falcon Air Express","USA"),
    FRJ_6F("6F","FRJ","Afrijet Airlines","Afrijet Airlines","Nigeria"),
    RLX_6G("6G","RLX","Go2Sky","Go2Sky","Slovakia"),
    ISR_6H("6H","ISR","Israir","Israir","Israel"),
    IBZ_6I("6I","IBZ","International Business Air","International Business Air","Sweden"),
    MMD_6I("6I","MMD","Alsie Express/MMD","Alsie Express/MMD","Denmark"),
    VVA_6I("6I","VVA","Aviast","Aviast","Russia"),
    JBW_6J("6J","JBW","Jubba Airways","Jubba Airways","Kenya"),
    SNJ_6J("6J","SNJ","Skynet Asia Airways","Skynet Asia Airways","Japan"),
    AKK_6L("6L","AKK","Aklak Air","Aklak Air","Canada"),
    DRU_6R("6R","DRU","Alrosa Mirny Air Enterprise","Alrosa Mirny Air Enterprise","Russia"),
    TNO_6R("6R","TNO","Aerounion/Aerotransporte de Carga Union","Aerounion/Aerotransporte de Carga Union","Mexico"),
    LMT_6T("6T","LMT","Almaty Aviation","Almaty Aviation","Kazakhstan"),
    SOV_6W("6W","SOV","Saravia Saratov Airlines","Saravia Saratov Airlines","Russia"),
    LTC_6Y("6Y","LTC","SmartLynx Airlines","SmartLynx Airlines","Latvia"),
    COY_7C("7C","COY","Coyne Airways","Coyne Airways","United Kingdom"),
    JJA_7C("7C","JJA","Jeju Air","Jeju Air","Korea – Rep. of"),
    AWU_7E("7E","AWU","Sylt Air","Sylt Air","Germany"),
    FAB_7F("7F","FAB","First Air","First Air","Canada"),
    SFJ_7G("7G","SFJ","StarFlyer","StarFlyer","Japan"),
    TLR_7Q("7Q","TLR","Air Libya","Air Libya","Libya"),
    RYA_7S("7S","RYA","Arctic Transportation Services/Ryan Air Services","Arctic Transportation Services/Ryan Air Services","USA"),
    AGV_7T("7T","AGV","Air Glaciers","Air Glaciers","Switzerland"),
    RTM_7T("7T","RTM","Aero Express Del Ecuador","Aero Express Del Ecuador","Ecuador"),
    TOB_7T("7T","TOB","Tobruk Air Transport and Cargo","Tobruk Air Transport and Cargo","Libya"),
    WRC_7W("7W","WRC","Wind Rose Aviation","Wind Rose Aviation","Ukraine"),
    AGO_7Y("7Y","AGO","Angola Air Charter","Angola Air Charter","Angola"),
    NYL_7Y("7Y","NYL","Mid Airlines","Mid Airlines","Sudan"),
    ATN_8C("8C","ATN","Air Transport International ATI","Air Transport International ATI","USA"),
    EXV_8D("8D","EXV","Expo Aviation","Expo Aviation","Sri Lanka"),
    BRG_8E("8E","BRG","Bering Air","Bering Air","USA"),
    STP_8F("8F","STP","STP Airways","STP Airways","Sao Tome and Principe"),
    HFR_8H("8H","HFR","Heli France","Heli France","France"),
    LKE_8L("8L","LKE","Lucky Air","Lucky Air","China"),
    RHC_8L("8L","RHC","Redhill Aviation","Redhill Aviation","United Kingdom"),
    MMA_8M("8M","MMA","Myanmar Airways International","Myanmar Airways International","Myanmar"),
    NKF_8N("8N","NKF","Barents AirLink/Nordkalottflyg","Barents AirLink/Nordkalottflyg","Sweden"),
    PCO_8P("8P","PCO","Pacific Coastal Airlines","Pacific Coastal Airlines","Canada"),
    OHY_8Q("8Q","OHY","Onur Air","Onur Air","Turkey"),
    OLS_8R("8R","OLS","Sol Lineas Aereas","Sol Lineas Aereas","Argentina"),
    AAW_8U("8U","AAW","Afriqiyah Airways","Afriqiyah Airways","Libya"),
    ACP_8V("8V","ACP","Astral Aviation","Astral Aviation","Kenya"),
    PWF_8W("8W","PWF","Private Wings Flugcharter","Private Wings Flugcharter","Germany"),
    CYZ_8Y("8Y","CYZ","China Postal Airlines","China Postal Airlines","China"),
    GGE_8Y("8Y","GGE","EGA Ecuato Guineana de Aviacion","EGA Ecuato Guineana de Aviacion","Equatorial Guinea"),
    EZX_9A("9A","EZX","Eaglexpress","Eaglexpress","Malaysia"),
    WDA_9C("9C","WDA","Wimbi Dira Airways","Wimbi Dira Airways","Congo – Democratic Rep."),
    THE_9D("9D","THE","Toumai Air Tchad","Toumai Air Tchad","Chad"),
    FLG_9E("9E","FLG","Endeavor Air","Endeavor Air","USA"),
    PGP_9G("9G","PGP","Perm Airlines","Perm Airlines","Russia"),
    DAN_9J("9J","DAN","Dana Air","Dana Air","Nigeria"),
    KAP_9K("9K","KAP","Cape Air","Cape Air","USA"),
    GLR_9M("9M","GLR","Central Mountain Air","Central Mountain Air","Canada"),
    NSE_9N("9N","NSE","SATENA","SATENA","Colombia"),
    VAP_9R("9R","VAP","Phuket Air","Phuket Air","Thailand"),
    CQH_9S("9S","CQH","Spring Airlines","Spring Airlines","China"),
    SOO_9S("9S","SOO","Southern Air","Southern Air","USA"),
    ABS_9T("9T","ABS","Transwest Air","Transwest Air","Canada"),
    RUN_9T("9T","RUN","ACT Airlines","ACT Airlines","Turkey"),
    MLD_9U("9U","MLD","Air Moldova","Air Moldova","Moldova"),
    AMV_9V("9V","AMV","AMC Airlines","AMC Airlines","Egypt"),
    ROI_9V("9V","ROI","Avior Airlines","Avior Airlines","Venezuela"),
    JAI_9W("9W","JAI","Jet Airways","Jet Airways","India"),
    AXY_9X("9X","AXY","New Axis Airways","New Axis Airways","France"),
    CIU_A2("A2","CIU","Cielos Airlines","Cielos Airlines","Peru"),
    AEE_A3("A3","AEE","Aegean Airlines","Aegean Airlines","Greece"),
    HOP_A5("A5","HOP","Hop!","Hop!","France"),
    BGL_A8("A8","BGL","Benin Golf Air","Benin Golf Air","Benin"),
    TGZ_A9("A9","TGZ","Georgian Airways/Air Zena","Georgian Airways/Air Zena","Georgia"),
    AAL_AA("AA","AAL","American Airlines","American Airlines","USA"),
    BER_AB("AB","BER","Air Berlin","Air Berlin","Germany"),
    ACA_AC("AC","ACA","Air Canada","Air Canada","Canada"),
    MDA_AE("AE","MDA","Mandarin Airlines","Mandarin Airlines","Taiwan"),
    ABR_AG("AG","ABR","Air Contractors","Air Contractors","Ireland"),
    DAH_AH("AH","DAH","Air Algerie","Air Algerie","Algeria"),
    AIA_AI("AI","AIA","Airmark Indonesia","Airmark Indonesia","Indonesia"),
    AIC_AI("AI","AIC","Air India","Air India","India"),
    NIG_AJ("AJ","NIG","Aero Contractors","Aero Contractors","Nigeria"),
    AXM_AK("AK","AXM","AirAsia","AirAsia","Malaysia"),
    TXC_AL("AL","TXC","Transaviaexport Cargo Airline","Transaviaexport Cargo Airline","Belarus"),
    AMX_AM("AM","AMX","Aeromexico","Aeromexico","Mexico"),
    ADH_AP("AP","ADH","Air One Smart Carrier","Air One Smart Carrier","Italy"),
    ARG_AR("AR","ARG","Aerolineas Argentinas","Aerolineas Argentinas","Argentina"),
    ASA_AS("AS","ASA","Alaska Airlines","Alaska Airlines","USA"),
    RAM_AT("AT","RAM","Royal Air Maroc","Royal Air Maroc","Morocco"),
    AUT_AU("AU","AUT","Austral Lineas Aereas","Austral Lineas Aereas","Argentina"),
    AVA_AV("AV","AVA","Avianca","Avianca","Colombia"),
    AWN_AW("AW","AWN","Air Niamey","Air Niamey","Niger"),
    SCH_AW("AW","SCH","CHC Airways","CHC Airways","Netherlands"),
    LOF_AX("AX","LOF","Trans States Airlines","Trans States Airlines","USA"),
    FIN_AY("AY","FIN","Finnair","Finnair","Finland"),
    AZA_AZ("AZ","AZA","Alitalia","Alitalia","Italy"),
    BRU_B2("B2","BRU","Belavia","Belavia","Belarus"),
    BCF_B4("B4","BCF","BACH Flugbetriebs","BACH Flugbetriebs","Austria"),
    BKA_B4("B4","BKA","Bankair","Bankair","USA"),
    EXZ_B5("B5","EXZ","East African Safari Air Express","East African Safari Air Express","Kenya"),
    JBU_B6("B6","JBU","JetBlue Airways {Jet Blue}","JetBlue Airways {Jet Blue}","USA"),
    UIA_B7("B7","UIA","UNI Airways Corporation","UNI Airways Corporation","Taiwan"),
    ERT_B8("B8","ERT","Eritrean Airlines","Eritrean Airlines","Eritrea"),
    IRB_B9("B9","IRB","Iran Air Tours","Iran Air Tours","Iran"),
    BAT_BA("BA","BAT","British Airways Limited","British Airways Limited","United Kingdom"),
    SHT_BA("BA","SHT","British Airways Shuttle","British Airways Shuttle","United Kingdom"),
    SBS_BB("BB","SBS","Seaborne Airlines","Seaborne Airlines","Virgin Islands – USA"),
    SKY_BC("BC","SKY","Skymark Airlines","Skymark Airlines","Japan"),
    BEE_BE("BE","BEE","flybe","flybe","United Kingdom"),
    FCM_BE("BE","FCM","flybe Nordic/Finnish Commuter Airlines","flybe Nordic/Finnish Commuter Airlines","Finland"),
    BBD_BF("BF","BBD","Bluebird Cargo","Bluebird Cargo","Iceland"),
    RSR_BF("BF","RSR","Aero-Service","Aero-Service","Congo"),
    BBC_BG("BG","BBC","Biman Bangladesh","Biman Bangladesh","Bangladesh"),
    BHA_BH("BH","BHA","Hawkair","Hawkair","Canada"),
    RBA_BI("BI","RBA","Royal Brunei Airlines","Royal Brunei Airlines","Brunei Darussalam"),
    BRJ_BJ("BJ","BRJ","Borajet","Borajet","Turkey"),
    LBT_BJ("BJ","LBT","Nouvelair","Nouvelair","Tunisia"),
    OKA_BK("BK","OKA","Okay Airways","Okay Airways","China"),
    PIC_BL("BL","PIC","Jetstar Pacific Airlines","Jetstar Pacific Airlines","Vietnam"),
    BMR_BM("BM","BMR","bmi Regional","bmi Regional","United Kingdom"),
    BBW_BO("BO","BBW","BB Airways","BB Airways","Nepal"),
    BOT_BP("BP","BOT","Air Botswana","Air Botswana","Botswana"),
    BBV_BQ("BQ","BBV","Bravo Airlines","Bravo Airlines","Spain"),
    EVA_BR("BR","EVA","EVA Airways Corporation","EVA Airways Corporation","Taiwan"),
    BIH_BS("BS","BIH","British International Helicopters","British International Helicopters","United Kingdom"),
    BTI_BT("BT","BTI","Air Baltic","Air Baltic","Latvia"),
    BPA_BV("BV","BPA","Blue Panorama Airlines/Blu-Express","Blue Panorama Airlines/Blu-Express","Italy"),
    BWA_BW("BW","BWA","Caribbean Airlines/Air Jamaica","Caribbean Airlines/Air Jamaica","Trinidad and Tobago"),
    ABL_BX("BX","ABL","Air Busan","Air Busan","Korea – Rep. of"),
    TOM_BY("BY","TOM","Thomson Airways","Thomson Airways","United Kingdom"),
    BBG_BZ("BZ","BBG","Bluebird Airways","Bluebird Airways","Greece"),
    BDA_BZ("BZ","BDA","Blue Dart Aviation","Blue Dart Aviation","India"),
    KEE_BZ("BZ","KEE","Keystone Air Service","Keystone Air Service","Canada"),
    CEL_C2("C2","CEL","CEIBA Intercontinental","CEIBA Intercontinental","Equatorial Guinea"),
    IMX_C4("C4","IMX","Zimex Aviation","Zimex Aviation","Switzerland"),
    UCA_C5("C5","UCA","Commutair","Commutair","USA"),
    CJA_C6("C6","CJA","CanJet","CanJet","Canada"),
    CIN_C7("C7","CIN","Cinnamon Air","Cinnamon Air","Sri Lanka"),
    CAO_CA("CA","CAO","Air China Cargo","Air China Cargo","China"),
    CCA_CA("CA","CCA","Air China","Air China","China"),
    CCD_CA("CA","CCD","Dalian Airlines","Dalian Airlines","China"),
    ABD_CC("CC","ABD","Air Atlanta Icelandic","Air Atlanta Icelandic","Iceland"),
    LLR_CD("CD","LLR","Air India Regional","Air India Regional","India"),
    TOK_CG("CG","TOK","Airlines PNG/Airlines of Papua New Guinea","Airlines PNG/Airlines of Papua New Guinea","Papua New Guinea"),
    BMJ_CH("CH","BMJ","Bemidji Airlines","Bemidji Airlines","USA"),
    CAL_CI("CI","CAL","China Airlines","China Airlines","Taiwan"),
    CFE_CJ("CJ","CFE","BA CityFlyer Express","BA CityFlyer Express","United Kingdom"),
    CKK_CK("CK","CKK","China Cargo Airlines","China Cargo Airlines","China"),
    CLW_CL("CL","CLW","LOT Charters","LOT Charters","Poland"),
    CMP_CM("CM","CMP","Copa Airlines","Copa Airlines","Panama"),
    GDC_CN("CN","GDC","Grand China Air","Grand China Air","China"),
    CPZ_CP("CP","CPZ","Compass Airlines","Compass Airlines","USA"),
    EXL_CQ("CQ","EXL","Sunshine Express Airlines","Sunshine Express Airlines","Australia"),
    CYL_CT("CT","CYL","Alitalia CityLiner","Alitalia CityLiner","Italy"),
    CUB_CU("CU","CUB","Cubana de Aviacion","Cubana de Aviacion","Cuba"),
    CLX_CV("CV","CLX","Cargolux","Cargolux","Luxembourg"),
    CVA_CV("CV","CVA","Air Chathams","Air Chathams","New Zealand"),
    MRS_CW("CW","MRS","Air Marshall Islands","Air Marshall Islands","Marshall Islands"),
    CPA_CX("CX","CPA","Cathay Pacific Airways","Cathay Pacific Airways","Hong Kong"),
    CYP_CY("CY","CYP","Cyprus Airways","Cyprus Airways","Cyprus"),
    CSN_CZ("CZ","CSN","China Southern Airlines","China Southern Airlines","China"),
    DHK_D0("D0","DHK","DHL Air UK/DHL Air Ltd","DHL Air UK/DHL Air Ltd","United Kingdom"),
    SSF_D2("D2","SSF","Severstal Aircompany","Severstal Aircompany","Russia"),
    DAO_D3("D3","DAO","Daallo Airlines","Daallo Airlines","Djibouti"),
    LID_D4("D4","LID","Alidaunia","Alidaunia","Italy"),
    DAE_D5("D5","DAE","DHL Aero Expreso","DHL Aero Expreso","Panama"),
    ILN_D6("D6","ILN","Inter Air","Inter Air","South Africa"),
    XAX_D7("D7","XAX","AirAsia X","AirAsia X","Malaysia"),
    DNV_D9("D9","DNV","Donavia","Donavia","Russia"),
    GAO_DC("DC","GAO","Golden Air","Golden Air","Sweden"),
    NOK_DD("DD","NOK","Nok Air","Nok Air","Thailand"),
    CFG_DE("DE","CFG","Condor Airlines","Condor Airlines","Germany"),
    DER_DF("DF","DER","Beijing Capital Airlines","Beijing Capital Airlines","China"),
    SRQ_DG("DG","SRQ","South East Asian Airlines","South East Asian Airlines","Philippines"),
    VOZ_DJ("DJ","VOZ","Virgin Australia Airlines","Virgin Australia Airlines","Australia"),
    PBN_DJ("DJ","PBN","Virgin Samoa","Virgin Samoa","Samoa"),
    VKG_DK("DK","VKG","Thomas Cook Airlines Scandinavia","Thomas Cook Airlines Scandinavia","Denmark"),
    DAL_DL("DL","DAL","Delta Air Lines","Delta Air Lines","USA"),
    SGG_DN("DN","SGG","Senegal Airlines","Senegal Airlines","USA"),
    CXT_DQ("DQ","CXT","Coastal Air Transport","Coastal Air Transport","USA"),
    EZS_DS("DS","EZS","easyJet Switzerland","easyJet Switzerland","Switzerland"),
    DTA_DT("DT","DTA","TAAG Angola Airlines","TAAG Angola Airlines","Angola"),
    NLH_DU("DU","NLH","Norwegian Long Haul","Norwegian Long Haul","Norway"),
    VSV_DV("DV","VSV","Scat Air/PLL Scat Aircompany","Scat Air/PLL Scat Aircompany","Kazakhstan"),
    UCR_DW("DW","UCR","Aero Charter Ukraine","Aero Charter Ukraine","Ukraine"),
    DTR_DX("DX","DTR","DAT Danish Air Transport","DAT Danish Air Transport","Denmark"),
    NAX_DY("DY","NAX","Norwegian Air Shuttle","Norwegian Air Shuttle","Norway"),
    RBG_E5("E5","RBG","Air Arabia Egypt","Air Arabia Egypt","Egypt"),
    ESF_E7("E7","ESF","Estafeta Carga Aerea","Estafeta Carga Aerea","Mexico"),
    GTA_E8("E8","GTA","City Airways","City Airways","Thailand"),
    EVE_E9("E9","EVE","Evelop Airlines","Evelop Airlines","Spain"),
    PLM_EB("EB","PLM","Pullmantur Air","Pullmantur Air","Spain"),
    BOS_EC("EC","BOS","OpenSkies","OpenSkies","United Kingdom"),
    TWN_EC("EC","TWN","Avialeasing Aviation Company","Avialeasing Aviation Company","Uzbekistan"),
    ABQ_ED("ED","ABQ","Airblue","Airblue","Pakistan"),
    ESY_EF("EF","ESY","EasyFly","EasyFly","Colombia"),
    ENJ_EG("EG","ENJ","Enerjet","Enerjet","Canada"),
    AKX_EH("EH","AKX","ANA Wings","ANA Wings","Japan"),
    EIN_EI("EI","EIN","Aer Lingus","Aer Lingus","Ireland"),
    NEA_EJ("EJ","NEA","New England Airlines","New England Airlines","USA"),
    UAE_EK("EK","UAE","Emirates","Emirates","United Arab Emirates"),
    AEB_EM("EM","AEB","Aero Benin","Aero Benin","Benin"),
    WTA_FK("FK","WTA","Africa West Airlines","Africa West Airlines","Togo"),
    TRS_FL("FL","TRS","Airtran Airways","Airtran Airways","USA"),
    CSH_FM("FM","CSH","Shanghai Airlines","Shanghai Airlines","China"),
    FTZ_FN("FN","FTZ","Fastjet","Fastjet","United Kingdom/Tanzania"),
    RGL_FN("FN","RGL","Royal Air Maroc Express/Regional Airlines","Royal Air Maroc Express/Regional Airlines","Morocco"),
    ATM_FO("FO","ATM","Airlines of Tasmania","Airlines of Tasmania","Australia"),
    FXX_FO("FO","FXX","Felix Airways","Felix Airways","Yemen"),
    FPG_FP("FP","FPG","TAG Aviation","TAG Aviation","Switzerland"),
    FRE_FP("FP","FRE","Freedom Air/Aviation Services","Freedom Air/Aviation Services","Guam"),
    TCW_FQ("FQ","TCW","Thomas Cook Airlines Belgium","Thomas Cook Airlines Belgium","Belgium"),
    RYR_FR("FR","RYR","Ryanair","Ryanair","Ireland"),
    SYA_FS("FS","SYA","Syphax Airlines","Syphax Airlines","Tunisia"),
    SDM_FV("FV","SDM","Rossiya Russian Airlines","Rossiya Russian Airlines","Russia"),
    FRI_FW("FW","FRI","Ibex Airlines","Ibex Airlines","Japan"),
    FDX_FX("FX","FDX","FedEx Express/Federal Express","FedEx Express/Federal Express","USA"),
    FFM_FY("FY","FFM","Firefly","Firefly","Malaysia"),
    NWR_FY("FY","NWR","Northwest Regional Airlines","Northwest Regional Airlines","Australia"),
    FDB_FZ("FZ","FDB","Flydubai","Flydubai","United Arab Emirates"),
    ADO_HD("HD","ADO","Hokkaido International Airlines/Air Do","Hokkaido International Airlines/Air Do","Japan"),
    LGW_HE("HE","LGW","LGW Luftfahrtgesellschaft Walter","LGW Luftfahrtgesellschaft Walter","Germany"),
    VRE_HF("HF","VRE","Air Côte d’Ivoire","Air Côte d’Ivoire","Cote d’Ivoire"),
    NLY_HG("HG","NLY","Niki","Niki","Austria"),
    TMN_HJ("HJ","TMN","Tasman Cargo Airlines","Tasman Cargo Airlines","Australia"),
    FSC_HK("HK","FSC","Four Star Air Cargo","Four Star Air Cargo","Virgin Islands – USA"),
    HAY_HK("HK","HAY","Hamburg Airways","Hamburg Airways","Germany"),
    SEY_HM("HM","SEY","Air Seychelles","Air Seychelles","Seychelles"),
    HVY_HN("HN","HVY","HeavyLift Cargo Airlines","HeavyLift Cargo Airlines","Australia"),
    PTH_HN("HN","PTH","Proteus Helicopteres","Proteus Helicopteres","France"),
    DKH_HO("HO","DKH","Juneyao Airlines","Juneyao Airlines","China"),
    HHN_HR("HR","HHN","Hahn Air","Hahn Air","Germany"),
    HSV_HS("HS","HSV","Svenska Direktflyg","Svenska Direktflyg","Sweden"),
    IMP_HT("HT","IMP","Hellenic Imperial Airways","Hellenic Imperial Airways","Greece"),
    CHH_HU("HU","CHH","Hainan Airlines","Hainan Airlines","China"),
    TRA_HV("HV","TRA","transavia.com/Transavia Airlines","transavia.com/Transavia Airlines","Netherlands"),
    NWL_HW("HW","NWL","North-Wright Airways","North-Wright Airways","Canada"),
    CRK_HX("HX","CRK","Hong Kong Airlines","Hong Kong Airlines","Hong Kong"),
    UZB_HY("HY","UZB","Uzbekistan Airways","Uzbekistan Airways","Uzbekistan"),
    SHU_HZ("HZ","SHU","Aurora","Aurora","Russia"),
    IBS_I2("I2","IBS","Iberia Express","Iberia Express","Spain"),
    FWA_I4("I4","FWA","Interstate Airlines","Interstate Airlines","Netherlands"),
    CMM_I5("I5","CMM","Air Mali","Air Mali","Mali"),
    SEQ_I6("I6","SEQ","Sky Eyes","Sky Eyes","Thailand"),
    IAW_IA("IA","IAW","Iraqi Airways","Iraqi Airways","Iraq"),
    IBE_IB("IB","IBE","Iberia","Iberia","Spain"),
    BTK_ID("ID","BTK","Batik Air","Batik Air","Indonesia"),
    SOL_IE("IE","SOL","Solomon Airlines","Solomon Airlines","Solomon Islands"),
    ISS_IG("IG","ISS","Meridiana Fly","Meridiana Fly","Italy"),
    MZA_IH("IH","MZA","Irtysh Air","Irtysh Air","Kazakhstan"),
    CSQ_II("II","CSQ","IBC Airways","IBC Airways","USA"),
    MNJ_IM("IM","MNJ","Menajet","Menajet","Lebanon"),
    IRA_IR("IR","IRA","Iran Air","Iran Air","Iran"),
    ISA_IS("IS","ISA","Island Airlines","Island Airlines","USA"),
    WON_IW("IW","WON","Wings Abadi Air","Wings Abadi Air","Indonesia"),
    FJA_FJ("FJ","FJA","Pacific Sun/Fiji Airlines","Pacific Sun/Fiji Airlines","Fiji"),
    VXG_G2("G2","VXG","Avirex Gabon","Avirex Gabon","Gabon"),
    AAY_G4("G4","AAY","Allegiant Air","Allegiant Air","USA"),
    GZD_G4("G4","GZD","Grizodubova Air Company","Grizodubova Air Company","Russia"),
    HXA_G5("G5","HXA","China Express Airlines","China Express Airlines","China"),
    GJS_G7("G7","GJS","GoJet Airlines","GoJet Airlines","USA"),
    ENK_G8("G8","ENK","Enkor","Enkor","Russia"),
    GOW_G8("G8","GOW","GoAir","GoAir","India"),
    ABY_G9("G9","ABY","Air Arabia","Air Arabia","United Arab Emirates"),
    GIA_GA("GA","GIA","Garuda Indonesia","Garuda Indonesia","Indonesia"),
    ABX_GB("GB","ABX","ABX Air","ABX Air","USA"),
    GCB_GC("GC","GCB","Lina Congo","Lina Congo","Congo"),
    GNR_GC("GC","GNR","Gambia International Airlines","Gambia International Airlines","Gambia"),
    TNA_GE("GE","TNA","TransAsia Airways","TransAsia Airways","Taiwan"),
    GFA_GF("GF","GFA","Gulf Air","Gulf Air","Bahrain"),
    GLP_GH("GH","GLP","Globus","Globus","Russia"),
    CDC_GJ("GJ","CDC","Zhejiang Loong Airlines","Zhejiang Loong Airlines","China"),
    JJP_GK("GK","JJP","JetStar Japan","JetStar Japan","Japan"),
    GRL_GL("GL","GRL","Air Greenland","Air Greenland","Denmark"),
    KZU_GO("GO","KZU","ULS Airlines Cargo Transport","ULS Airlines Cargo Transport","Turkey"),
    GDR_GP("GP","GDR","Gadair European Airlines","Gadair European Airlines","Spain"),
    GES_GP("GP","GES","Gestair","Gestair","Spain"),
    SEH_GQ("GQ","SEH","Sky Express","Sky Express","Greece"),
    AUR_GR("GR","AUR","Aurigny Air Services","Aurigny Air Services","United Kingdom"),
    GCR_GS("GS","GCR","Tianjin Airlines","Tianjin Airlines","China"),
    JXX_GX("GX","JXX","Primera Air","Primera Air","Iceland"),
    GBK_GY("GY","GBK","Gabon Airlines","Gabon Airlines","Gabon"),
    TMG_GY("GY","TMG","Tri-MG Intra Asia Airlines","Tri-MG Intra Asia Airlines","Indonesia"),
    SKU_H2("H2","SKU","Sky Airline","Sky Airline","Chile"),
    HRM_H3("H3","HRM","Hermes Airlines","Hermes Airlines","Greece"),
    HLI_H4("H4","HLI","Heli Securite Helicopter Airlines","Heli Securite Helicopter Airlines","France"),
    RSY_H5("H5","RSY","I-Fly","I-Fly","Russia"),
    HAG_H6("H6","HAG","Hageland Aviation Services","Hageland Aviation Services","USA"),
    EGU_H7("H7","EGU","Eagle Air","Eagle Air","Uganda"),
    HTH_H9("H9","HTH","Helitt Lineas Aereas","Helitt Lineas Aereas","Spain"),
    HAL_HA("HA","HAL","Hawaiian Airlines","Hawaiian Airlines","USA"),
    AAQ_HB("HB","AAQ","Asia Atlantic Airlines","Asia Atlantic Airlines","Thailand"),
    NOTSET("NOTSET","NOTSET","NOTSET","NOTSET","NOTSET");


    private final String iata;
    private final String icao;
    private final String airline;
    private final String airlineTR;
    private final String country;

    private AirlineEnum(String iata, String icao, String airline, String airlineTR, String country) {
	this.iata =  iata;
	this.icao = icao;
	this.airline = airline;
	this.airlineTR = airlineTR;
	this.country = country;
    }
    
    public static AirlineEnum getByIata(String iata) {
	for (AirlineEnum type : AirlineEnum.values()) {
	    if (type.iata.equals(iata)) {
		return type;
	    }
	}
	return AirlineEnum.NOTSET;
    }
    
    public String getAirline() {
	return this.airline;
    }
    
    public String getAirlineTR() {
	return this.airlineTR;
    }

}
