spring:
  datasource:
    url: jdbc:mysql://mysqlserver:3306?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: dbuser
    password: Db*12345678
    driver-class-name: com.mysql.jdbc.Driver
